version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=whistledb
    volumes:
     - "datastore:/var/lib/postgresql"
  postgres-admin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_PASSWORD=pass
      - PGADMIN_DEFAULT_EMAIL=louis.nourigeon@labsd.net
volumes:
  datastore: