# Generated by Django 4.0.2 on 2022-02-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalinfo',
            name='hypertension',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
