# Generated by Django 4.0.2 on 2022-02-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientmedicalinfo_hypertension'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mr_code',
            field=models.PositiveIntegerField(),
        ),
    ]
