# Generated by Django 4.0.2 on 2022-02-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_patient_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='patient',
            index_together=set(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
