# Generated by Django 4.0.2 on 2022-02-21 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patient_index_together_alter_patient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='patients.patient'),
        ),
    ]
