# Generated by Django 4.0.2 on 2022-02-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_image_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='num',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
