# Generated by Django 4.0.2 on 2022-02-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_image_num'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('patient', 'num')},
        ),
    ]
