# Generated by Django 4.0.2 on 2022-02-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_image_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='health_insurence_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='health_insurance_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
